# Generated by Django 2.2 on 2019-08-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='news_story',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
