# Generated by Django 2.2 on 2019-08-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190808_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Artist'),
        ),
    ]
