# Generated by Django 2.2 on 2019-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsitem_news_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
