# Generated by Django 2.2 on 2019-08-05 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
