# Generated by Django 2.2 on 2019-08-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsitem_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='artist',
        ),
    ]
