# Generated by Django 2.2 on 2019-08-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
