# Generated by Django 2.2 on 2019-08-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_newsitem_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='athlete_media/')),
                ('name', models.CharField(default='athlete', max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='core.Category')),
            ],
        ),
    ]
