# Generated by Django 2.2 on 2019-08-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190806_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
