# Generated by Django 2.2 on 2019-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190806_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
